### PR TITLE
Split lines of code into lines of text

### PR DESCRIPTION
**Pull request by l0b0**
The original text had two lines of code per line of text, making it harder to match with the line-by-line explanation in the next code block.

### CODE REVIEW

**Comment by autotelicum** [comment]
It's likely that the formatting was chosen to get the PDF to look right. I'll look into it when I - in some days - get to my notebook. I only have some tools on debian running on my mobile phone.

**Comment by autotelicum** [comment]
Showing six or three bytes (the blocks of eight 0's and 1's) on a line is arbitrary. The length of actual CPU instructions can vary from one instruction to the next depending on the architecture. The line numbers that are referred to in the next section relate to that section itself, where there are line numbers on the left hand side.

If you are reading the LyX source document in LyX or in a text editor then you can not see those line numbers, they are generated by LyX with the linenumbers=left setting on the section; I guess that is why you suggest this change, but the document is really meant to be read in the generated PDF format, not in the LyX source format.

If you prefer to read the book in a text editor then the markdown version is easier to read ([it](https://raw.github.com/autotelicum/Smooth-CoffeeScript/gh-pages/interactive/interactive-coffeescript.md) is in the `gh-pages` branch). There you can see the line numbers on lines 677-686. I do suggest to read one of the generated versions in PDF or in HTML5 instead.

**Comment by l0b0** [comment]
I was referring to the [interactive web version](http://autotelicum.github.com/Smooth-CoffeeScript/interactive/interactive-coffeescript.html), where I got momentarily stumped when seeing "Each line of the program contains a single instruction." and then a nine-line explanation for a five-line set of binary output. Since each set of 3x8 bits is an instruction + parameters, it makes much more sense to put them on separate lines. Suggest to reopen.

**Comment by autotelicum** [comment]
I see what you mean now, thanks for pointing it out. The interactive version is generated from [this markdown file](https://raw.github.com/autotelicum/Smooth-CoffeeScript/gh-pages/interactive/interactive-coffeescript.md), not the LyX file in the pull request, but it goes for both.

LyX generates superior PDF, but unfortunately can not generate the quality of HTML that Pandoc produces, so the two versions are created from separate sources. I think in the PDF version it will not affect page breaks on the following pages too much, so it should be possible.

Creating a new edition takes some hours with verification, change logs, uploads etc. So I'll keep this in mind for the next edition. I think there will be sufficient reason to create a new edition when debugging in CoffeeScript becomes a reality (plus the recent changes regarding "use strict").

**Comment by l0b0** [comment]
Closing because of lack of interest.

**Pull request closed without merging**
